FROM node:16-alpine
EXPOSE 5000
WORKDIR /usr/src/app
COPY ./example-frontend .

RUN npm install && \
    npm run build && \
    npm install -g serve && \
    adduser -D webservice

USER webservice
CMD serve -s -l 5000 build
