FROM golang:1.16
WORKDIR /usr/src/app
COPY ./example-backend .
RUN go build
RUN go test ./... .
CMD ./server
ENV PORT=8000
#ENV REQUEST_ORIGIN=http://dockerhost
EXPOSE 8000
ENV REDIS_HOST=redis
ENV POSTGRES_HOST=db
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DATABASE=postgres
