version: '3.8'

services:
    example-frontend:
      image: example-frontend
      build: .
      container_name: example-frontend
    example-backend:
      image: example-backend
      restart: unless-stopped
      build: .
      container_name: example-backend
    redis:
      image: redis
      build: .
      container_name: redis
    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
      container_name: db
      volumes:
        - ./database:/var/lib/postgresql/data
    nginx:
      image: nginx
      build: .
      container_name: nginx-proxy
      ports:
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  db:
  nginx:
