version: '3.8'

services:
    youtube-dl-ubuntu:
      image: devopsdockeruh/simple-web-service:ubuntu
      build: .
      volumes:
        - ./text.log:/usr/src/app/text.log
      container_name: simple-web-service
