version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
      -  WATCHTOWER_LABEL_ENABLE=true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower

  express-app:
    image: hakmii/express-app
    restart: unless-stopped
    container_name: express-app
    ports:
      - 8080:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
