version: '3.8'

services:
    youtube-dl-ubuntu:
      image: devopsdockeruh/simple-web-service:ubuntu
      build: .
      container_name: simple-web-service
      ports:
        - 8080:8080
      command: ["server"]
