FROM node:16
EXPOSE 5000
WORKDIR /usr/src/app
COPY ./example-frontend .

RUN npm install && \
    npm run build && \
    npm install -g serve && \
    adduser webservice && \
    chown webservice .

USER webservice
CMD serve -s -l 5000 build
