FROM node:16-alpine as build-stage
WORKDIR /usr/src/app
COPY ./example-frontend .

RUN npm install && \
    npm run build && \
    npm install -g serve

# new stage
FROM node:16-alpine
EXPOSE 5000

COPY --from=build-stage /usr/src/app/build /usr/src/app

USER node
CMD serve -s -l 5000 build
